### ISSUE TITLE
이슈 템플릿 체크 실습

### ISSUE THREAD

**Issue by soulhn** [soulhn/my-test-repo#2]
### 만들고자 하는 기능은 무엇인가요?
ex) Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] Job1
2. [] Job2
3. [] Job3

### 예상 작업 시간
1h

**Comment by soulhn** [comment]
이슈 블랭크가 잘 안되는 것 같습니다.

**Comment by Gonue** [comment]
잘되는데요
