### ISSUE TITLE
Github Project Kanban 실습

### ISSUE THREAD

**Issue by soulhn** [soulhn/my-test-repo#4]
### 만들고자 하는 기능은 무엇인가요?
ex) Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] Job1
2. [ ] Job2
3. [ ] Job3

### 예상 작업 시간
1h

**Comment by Gonue** [comment]
👍

**Comment by soulhn** [comment]
닫습니다.
